model:
  base_model_id: "ibm-granite/granite-4.0-350m"
  model_path: "./models/granite-4.0-350m"

data:
  data_path: "./data/ultrafeedback_binarized"
  output_dir: "./outputs"

lora:
  r: 16
  alpha: 32
  dropout: 0.05

training:
  epochs: 1
  batch_size: 2
  grad_accum: 4
  logging_steps : 10
  eval_steps: 100
  save_steps: 100
  learning_rate: 0.0002
  max_length: 512

mlflow:
  tracking_uri: "sqlite:///mlruns.db"
  experiment_name: "granite-350M-sft-ultrafeedback"